// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrvoh5Nus7x0dSDKz_2FGJWJ7ouksE34Q',
    appId: '1:853599875468:web:74d2bb94c22a82b87da6a9',
    messagingSenderId: '853599875468',
    projectId: 'feelong-f3885',
    authDomain: 'feelong-f3885.firebaseapp.com',
    storageBucket: 'feelong-f3885.firebasestorage.app',
    measurementId: 'G-9C1N3RPVBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2UNL-vB4AHVWT_VjzmN6pNPrWhwwYpwg',
    appId: '1:853599875468:android:6a341b2740f6cc567da6a9',
    messagingSenderId: '853599875468',
    projectId: 'feelong-f3885',
    storageBucket: 'feelong-f3885.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQanIef5sdtgmXgKzQT3p1y7A3-RuMwLo',
    appId: '1:853599875468:ios:0e9c33d1509456837da6a9',
    messagingSenderId: '853599875468',
    projectId: 'feelong-f3885',
    storageBucket: 'feelong-f3885.firebasestorage.app',
    iosBundleId: 'com.feelong.app',
  );
}
