import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: SafeArea(
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              child: Row(
                children: [
                  IconButton(
                    onPressed: () => Navigator.of(context).pop(),
                    icon: const Icon(
                      Icons.arrow_back_ios,
                      color: AppColors.textMuted,
                      size: 20,
                    ),
                  ),
                  const Expanded(
                    child: Text(
                      'Terms of Service',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: AppColors.textPrimary,
                        fontSize: 16,
                      ),
                    ),
                  ),
                  const SizedBox(width: 48),
                ],
              ),
            ),
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(24),
                child: Center(
                  child: ConstrainedBox(
                    constraints: BoxConstraints(maxWidth: kIsWeb ? 480 : double.infinity),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _sectionTitle('Last Updated'),
                        _body('March 6, 2026'),
                        const SizedBox(height: 20),
                        _sectionTitle('Acceptance of Terms'),
                        _body(
                          'By using Innerscape ("the app"), you agree to these Terms of Service. '
                          'If you do not agree, please do not use the app.',
                        ),
                        const SizedBox(height: 20),
                        _sectionTitle('Description of Service'),
                        _body(
                          'Innerscape is a mood journaling app that provides AI-powered reflections, '
                          'breathing exercises, wellness tips, and emotional tracking tools. The app '
                          'is provided for personal, non-commercial use.',
                        ),
                        const SizedBox(height: 20),
                        _sectionTitle('Not Medical Advice'),
                        _body(
                          'Innerscape is a wellness tool, not a medical or mental health service. '
                          'AI-generated reflections and suggestions are not professional advice. '
                          'If you are experiencing a mental health crisis, please contact a qualified '
                          'professional or emergency services immediately.',
                        ),
                        const SizedBox(height: 20),
                        _sectionTitle('User Responsibilities'),
                        _body(
                          '- You are responsible for the content you enter into the app.\n'
                          '- You are responsible for maintaining access to your device and data.\n'
                          '- You agree not to misuse the app or attempt to access it through unauthorized means.',
                        ),
                        const SizedBox(height: 20),
                        _sectionTitle('Data and Storage'),
                        _body(
                          'Your data is stored locally on your device. We are not responsible for '
                          'data loss due to device failure, app deletion, or use of the "Reset All Data" '
                          'feature. There is no cloud backup.',
                        ),
                        const SizedBox(height: 20),
                        _sectionTitle('AI-Generated Content'),
                        _body(
                          'AI reflections and insights are generated by Google\'s Gemini API and may '
                          'not always be accurate, appropriate, or helpful. We do not guarantee the '
                          'quality or suitability of AI-generated content.',
                        ),
                        const SizedBox(height: 20),
                        _sectionTitle('Intellectual Property'),
                        _body(
                          'The app design, code, and branding are the property of Innerscape. '
                          'Your journal entries and personal data remain yours.',
                        ),
                        const SizedBox(height: 20),
                        _sectionTitle('Limitation of Liability'),
                        _body(
                          'Innerscape is provided "as is" without warranty of any kind. We are not '
                          'liable for any damages arising from your use of the app, including but '
                          'not limited to data loss, emotional distress, or reliance on AI-generated content.',
                        ),
                        const SizedBox(height: 20),
                        _sectionTitle('Changes to Terms'),
                        _body(
                          'We may update these terms at any time. Continued use of the app after '
                          'changes constitutes acceptance of the new terms.',
                        ),
                        const SizedBox(height: 20),
                        _sectionTitle('Contact'),
                        _body('For questions about these terms, reach out via the app\'s GitHub repository.'),
                        const SizedBox(height: 40),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  static Widget _sectionTitle(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Text(
        text.toUpperCase(),
        style: const TextStyle(
          fontSize: 11,
          color: AppColors.accent,
          letterSpacing: 1.5,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  static Widget _body(String text) {
    return Text(
      text,
      style: const TextStyle(
        fontSize: 14,
        color: AppColors.textMuted,
        height: 1.7,
      ),
    );
  }
}
